name: Sync with Template Repository

on:
    workflow_dispatch:

jobs:
  sync_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          ref: main  # Branch to merge changes into

      - name: Configure Git for merge
        run: |
          git config --global user.name "github-actions" 
          git config --global user.email "actions@users.noreply.github.com"

      - name: Add template repository as a remote
        run: git remote add template https://github.com/CU-ESIIL/Working_group_OASIS

      - name: Fetch updates from template
        run: git fetch template

      - name: Check for merge conflicts (informational)
        run: git merge template/main --check  # Check for conflicts without merging

      - name: Identify new files from template (optional)
        run: |  # Example using GNU Parallel (if installed)
          git fetch --depth=1 template/main  # Shallow clone for efficiency
          git diff --name-only --diff-filter=A template/main | parallel --no-notice echo {} >> new_files.txt

      - name: Merge non-conflicting changes (if no conflicts)
        run: |  
          if [[ $(git merge template/main --check 2>&1 | grep 'conflicts') ]]; then
              echo "Merge conflicts detected! Manual resolution required."
          else
              git merge template/main
          fi

      - name: Push changes to target repository (if merged)
        uses: actions/checkout@v3  # Use checkout to persist changes 
        with:
          token: ${{ secrets.ACCESS_TOKEN }}
          condition: success()  # Only push if previous step succeeded
