name: Sync with Template Repository

on:
    workflow_dispatch:

jobs:
  sync_template:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout target repository
        uses: actions/checkout@v3
        with:
          ref: main  # Branch to merge changes into

      - name: Configure Git for merge
        run: |
          git config --global user.name "github-actions" 
          git config --global user.email "actions@users.noreply.github.com"

      - name: Add template repository as a remote
        run: git remote add template https://github.com/CU-ESIIL/Working_group_OASIS

      - name: Fetch updates from template
        run: git fetch template

      - name: Merge changes from template
        run: git merge template/main --allow-unrelated-histories 

      - name: Push changes to target repository
        uses: actions/checkout@v3 # Use checkout to persist changes 
        with:
          token: ${{ secrets.ACCESS_TOKEN }} 